CC = g++ -std=c++11
exe_file = Senna_Titcomb_Austin_Friedrich_AIA1.exe
$(exe_file): graphmaker.o bfs.o dfs.o Senna_Titcomb_Austin_Friedrich_AIA1.o
	$(CC) graphmaker.o bfs.o dfs.o Senna_Titcomb_Austin_Friedrich_AIA1.o -o $(exe_file)
graphmaker.o: graphmaker.cpp graphmaker.h 
	$(CC) -c graphmaker.cpp
bfs.o: bfs.cpp bfs.h 
	$(CC) -c bfs.cpp
dfs.o: dfs.cpp dfs.h 
	$(CC) -c dfs.cpp
Senna_Titcomb_Austin_Friedrich_AIA1.o: Senna_Titcomb_Austin_Friedrich_AIA1.cpp
	$(CC) -c Senna_Titcomb_Austin_Friedrich_AIA1.cpp
clean:
	rm -f *.out *.o $(exe_file)
